#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus           off
yabai -m config focus_follows_mouse           off
yabai -m config window_origin_display         default
yabai -m config window_placement              second_child
yabai -m config window_topmost                on
yabai -m config window_shadow                 off
yabai -m config window_animation_duration     0.0
yabai -m config window_opacity_duration       0.0
yabai -m config active_window_opacity         1.0
yabai -m config normal_window_opacity         0.85
yabai -m config window_opacity                on
yabai -m config insert_feedback_color         0xffd75f5f
yabai -m config active_window_border_color    0xffffcfa1
yabai -m config normal_window_border_color    0xff555555
yabai -m config window_border_width           2
yabai -m config window_border_radius          12
yabai -m config window_border_blur            off
yabai -m config window_border_hidpi           on
yabai -m config window_border                 on
yabai -m config split_ratio                   0.50
yabai -m config split_type                    auto
yabai -m config auto_balance                  off
yabai -m config top_padding                   4
yabai -m config bottom_padding                14
yabai -m config left_padding                  14
yabai -m config right_padding                 14
yabai -m config window_gap                    14
yabai -m config layout                        bsp
yabai -m config mouse_modifier                 fn
yabai -m config mouse_action1                 move
yabai -m config mouse_action2                 resize
yabai -m config mouse_drop_action             swap

# Floating windows rules
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='Skype' manage=off

# Spaces' names
# yabai -m space 1 --label ∑
# yabai -m space 2 --label '</>'
# yabai -m space 3 --label '>_'
# yabai -m space 4 --label {}

echo "yabai configuration loaded.."
